### ISSUE TITLE
Intersections not working with partial read access

### ISSUE THREAD

**Issue by elaval** [firebase/firebase-util#12]
Not sure if this is an issue or if I don't know how to configure firebase-util correctly,  but I am having problems accessing records in the following cases (when I apply firebase security rules)

List of posts from a given user:
/users/{userId}/posts/{postId}/true

All posts with detailed information (and a list of users who have access to them)
/posts/{postId}/users/{userId}true

I have configured my firebase access rules to:
- Allow read access to the posts list for authenticated user
- Allow read access ONLY to the posts information which have the user in its users list

When I use a firebase-util intersection , I get an empty result because the user does not have read access to the whole /posts ref  (if open full read access it works).

I guess that if firebase-util intersection requires to load both full lists before going for the intersection the access rules will fail.  BUT if it tries to access all the posts from one list (the users/posts list) and then just the matching posts from /posts ... it might work.  How does it actually work?

Is it a requirement of the firebase-util to have full read rights to the complete sets of intersecting resources?

**Comment by katowulf** [comment]
Next refresh is 0.2 going out this week. Intersections will be implicit based on the first ref provided, which is considered the *master*.
