### ISSUE TITLE
new version?

### ISSUE THREAD

**Issue by georgesboris** [firebase/firebase-util#16]
Hey kato.
 I asked you a month ago about the compatibility with the new firebase and you said you would eventually get into it. Not trying to press the same button twice but do you have any idea of when can we expect that to be?

I'm using your module on a production app that will be shipped on April 2015. 
It's working wonders even with the new firebase. Only problem so far is the huge number of warnings.
Are you planning on working on it again in this next 4 months or is this not really in your plans right now?

I would gladly help if it's just a matter of suppressing the warnings by changing the name() to key() methods. I'm not very confident in doing anything beyond that though...

Cheers

**Comment by katowulf** [comment]
New release 0.2 scheduled for this week or next.
