### ISSUE TITLE
Applying filter to a NormalizedCollection doesn't work

### ISSUE THREAD

**Issue by maksymilian-majer** [firebase/firebase-util#29]
Calling `.filter()` on `NormalizedCollection` doesn't filter out the results. Here's an example:
http://plnkr.co/edit/3WRXrvtkxsHMnxHX0DRe

**Comment by katowulf** [comment]
It looks correct to me; returned exactly one record matching the filter:

![image](https://cloud.githubusercontent.com/assets/959972/6943762/fd75a804-d844-11e4-857d-bf69b9732ea2.png)

**Comment by maksymilian-majer** [comment]
You're right, but `$firebaseArray(ref)` still shows all results, so I played around some more.

When I attach `on('value',...)` the callback gets only one result - **bruce**, but when I attach `on('child_added',...)` the callback is called twice and both users are logged.

I've updated the plunk so you can investigate this:
http://plnkr.co/edit/3WRXrvtkxsHMnxHX0DRe

**Comment by maksymilian-majer** [comment]
I closed the issue by mistake.
