### ISSUE TITLE
Outdated description?

### ISSUE THREAD

**Issue by georgesboris** [firebase/firebase-util#31]
The current description of this repo read as follows:
"Firebase Utilities: A Firebase wrapper that joins several paths either as a union or intersection of the merged data sets."

But by what I've read in the updated docs, and by what I've tried to fiddle on my own, the union aspect has been taken out of this tool, right? As the normalized collection tries to merge different properties of different paths, but would not work in a path like this one:

/:activeTasks/:userId/[:taskId, :taskId]
/:completedTasks/:userId/[:taskId, :taskId]

In this case I would only need the joined path of both nodes.
Is this functionality really taken out of the toolset (and therefore the description outdated) or am I missing something?

Thanks

**Comment by katowulf** [comment]
Check out the docs for NormalizedCollection; You can merge on keys or values: http://firebase.github.io/firebase-util/#/toolbox/NormalizedCollection/

**Comment by jwngr** [comment]
The description has been updated.
