### ISSUE TITLE
Error using orderByValue() on NormalizedCollection

### ISSUE THREAD

**Issue by michaeldim** [firebase/firebase-util#32]
Related to: #28, I can't seem to apply a query on the master index using the orderByValue() method.  An 'undefined is not a function' error is returned, http://plnkr.co/edit/HaA1lz

**Comment by 111studio** [comment]
I think you should use orderByChild() instead.

**Comment by michaeldim** [comment]
There aren't any children to order by in the master index.

**Comment by katowulf** [comment]
Note that you can use orderByValue() on the master ref (e.g. `fb.child('event1').orderByValue()`) before passing it into NormalizedCollection to achieve the same effect and improve efficiency.

**Comment by michaeldim** [comment]
@katowulf Once the NormalizedCollection is added, even if orderByValue() is passed in the master ref it still doesn't order correctly.  http://plnkr.co/edit/VP9k5.  I'm not particularly concerned now you have added a fix, but I thought it worth mentioning.

**Comment by katowulf** [comment]
Will be fixed soon, probably today. orderByValue() on the master ref achieves the same effect.

**Comment by michaeldim** [comment]
OK thanks.

**Comment by michaeldim** [comment]
@katowulf Using the master branch 948cc685e01baf19a32832f44f14053818609ce5, queries still don't appear to be working on the index ref, http://plnkr.co/edit/GR6iAo?p=preview

**Comment by katowulf** [comment]
@michaeldim The title of this issue is "Error using orderByValue()"; I don't see that error being thrown in your plunker. Although I do see that limitToFirst() isn't working (which sounds like a new issue).

**Comment by michaeldim** [comment]
Ok ill open up a new issue for limitToFirst().  Although orderByValue is not sorting the data in the correct order.

**Comment by katowulf** [comment]
Also not the problem described here, but probably worthy of an issue.
