### ISSUE TITLE
When using filter(), on('child_added',...) and on('child_removed',...) are not working properly after child_changed

### ISSUE THREAD

**Issue by AaronJPA** [firebase/firebase-util#33]
When using `filter()`, `on('child_added',...)` and `on('child_removed',...)` are not working properly after `child_changed` on master index or on secondary path. Seems that `filter()` is not reapplied properly.

I'm opening four different issues because I'm not sure if they are related and, if they are not, they can be fixed separately. However, I used the same Plunker to simulate all of them, so it is a little bigger than usual. I tried to explain everything in the comments, but if something is not clear enough, just let me know.

http://plnkr.co/edit/Y0mp2XDtSQ0Pz9ClXctZ

**Comment by katowulf** [comment]
Cheers, again for the great repos. Hope to get out a release out with these fixes (and new test units!) Monday.

**Comment by AaronJPA** [comment]
What a great news! This issue is the one that was causing me most of the trouble! Thank you for the fixes!

**Comment by katowulf** [comment]
I've probably mentioned this already, but for the sake of others finding this discussion:  Note if if at all possible, one should put the filter values in the master list. Then a query can be passed into NormalizedCollection rather than using the filter() function. This makes things much more efficient by doing this server-side.

```
var masterRef = new Firebase(...).child(...).orderByChild( filterField ).equalTo( filterValue );
var nc = new NormalizedCollection( masterRef, mergedPath ).select(...).ref();
```

Cheers,
Kato

**Comment by AaronJPA** [comment]
Got it!

But the thing is that I was using the filter to turn the left join into an inner join. Something like

```
norm = norm.filter(
    function (data) { return data.anySecondaryPathField : true ? false; }
);
```

Cheers,
Aaron
