### ISSUE TITLE
Firebase utils : Scroll + Normalize 

### ISSUE THREAD

**Issue by mellinas** [firebase/firebase-util#37]
Hi, 
I got a warning/error when I try to mix multiple things (scroll, normalize, $firebaseArray)

var fb = new Firebase(FIREBASE_URL)
var ref = fb.child("users/user1/posts");
var postsRef = fb.child("posts");
var scrollRef = new Firebase.util.Scroll(ref,'$priority');
var norm = new Firebase.util.NormalizedCollection(scrollRef, postsRef).select('posts.from', 'posts.content', 'posts.time');
var userPosts = $firebaseArray(norm.ref());
userPosts.scroll = scrollRef.scroll;
return userPosts;

with the following structure :
{
  users: {
    user1: {
      name: "Alice",
      posts: {
        post1: true,
        post3: true,
        ... (let's assume there are 100 other posts)
      }
    },
    user2: {
      name: "Bob",
      posts: {
        post2: true
      }
    }
  },
  posts: {
    post1: {
	  content: "Hi"
          from: user1,
          time: 1428933171010
      },
      post2: {
	  content: "Welcome",
          from: user2,
          time: 1428933171011
      },  
      post3: {
	 content: "Ya"
         from: user1,
         time: 1428933171012
      }
  }
}

Here is the error/warning in JavaScript console : "this.off is not a function"

**Comment by mellinas** [comment]
It was only a this which was not available (inside the once function) : 

 'once': function(event, callback, cancel, context) {
    var that = this;
    function fn(snap) {
      /*jshint validthis:true */
      that.off(event, fn, this);  
      callback.call(context, snap);
    }
    this.on(event, fn, cancel, this);
  },

Line 3097/3098

Hope this helps :)

**Comment by katowulf** [comment]
Nice! Will fix this up.

**Comment by mellinas** [comment]
Great ! Thanks

**Comment by cameronbourke** [comment]
Yeah I'm having the same issue!

**Comment by katowulf** [comment]
@cameronbourke apply the fix provided by @mellinas; I'll add it into the next release.
