### ISSUE TITLE
Failed to instantiate module firebaseUtil

### ISSUE THREAD

**Issue by realph** [firebase/firebase-util#43]
I've building an AngularFire project using browserify, and have installed Firebase-util via npm. I've required it like so:

    var firebase = require('firebase');
    var firebaseUtil = require('firebase-util');
    var angularFire = require('angularfire');

And have included it as a dependency it in my `angular.module()` like this:

    angular.module('outcomesApp', [
      'firebase',
      'firebaseUtil',
      ...
    ])

But for some reason I'm getting this error:

    Uncaught Error: [$injector:modulerr] Failed to instantiate module outcomesApp due to:
    Error: [$injector:modulerr] Failed to instantiate module firebaseUtil due to:
    Error: [$injector:nomod] Module 'firebaseUtil' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

Any idea why this isn't working for me? Any help is appreciated. Thanks in advance!

**Comment by katowulf** [comment]
There is no `firebaseUtil` to inject in your AngularApp. Firebase-util is not an angular module. Not sure what instructions you're following here, but I'd recommend the docs on [getting started](http://firebase.github.io/firebase-util/#/).

**Comment by realph** [comment]
I've taken `firebaseUtil` out of the app. Following the demo, but still getting an error that `$scrollArray is not defined`.

**Comment by katowulf** [comment]
What demo are you following and what does your code look like? If you want an expedient answer to your questions, you'll need to be specific. 

The best way to get help troubleshooting your code is nearly always the same:  provide a [minimal, complete, verifiable example](http://stackoverflow.com/help/mcve) that demonstrates your issue. This should be one HTML page plus JavaScript and it should contain only the code needed to recreate the conditions you want help with.

Not only does this nearly always get a direct and immediate answer, but it will also enforce an effective paradigm for troubleshooting bugs, which will serve you extremely well and resolve most of your questions in the process: reducing the problem set until the cause of the error is obvious.

**Comment by realph** [comment]
Will follow this up with a proper dedicated issue. Thanks @katowulf.
