### ISSUE TITLE
Ionic Infinite scroll 

### ISSUE THREAD

**Issue by mcxolani** [firebase/firebase-util#45]
Hi I am developing an app using ionic and I was using the infinite scroll from firebase-util. My problem is I want latest data first just like in twitter and then scroll down to older posts

**Comment by michaeldim** [comment]
I don't think this is currently possible. #25

**Comment by mellinas** [comment]
It's possible but complicated
When you create your data, give a priority or create a specific child with the negative current timestamp
Then, when you use firebase-util infinite scroll, use orderByPriority or by your specific child
You will get data in reverse order then use InfiniteScroll on it to only get the one you want to display

**Comment by mcxolani** [comment]
Hi mellinas,
Thanks it works, I used the negative timestamp on child.
