### ISSUE TITLE
Does Firebase offload the computation for `NormalizedCollection` ?

### ISSUE THREAD

**Issue by gigablox** [firebase/firebase-util#50]
Haven't stepped through the source yet although I've played around with some of the joins.

Couple questions about where the computations are happening.

Is this library just resolving a bunch of Firebase requests through a promise array or is a single payload returned for something like a join on multiple ID's?

I do joins of my own through service logic and I'm trying to figure out if I'm gaining any performance by using this utility.

Does this utility send a single payload and receive a single payload?... Or is this just a utility that makes it easier to compile promise arrays and join data once it all comes back?

*Example:*

Say I want to get all the messages from Jim's users object:

```js
/*
 *    /users/-Ji28d73hd73h
 */

'name':'Jim',
'messages':{
  '-J8274629dj3':true,
  '-Ji27d7dh38d':true
}


/*
 *    /messages
 */

'-J8274629dj3':{
  text:'lol bro'
},
'-Ji27d7dh38d':{
  text:'u wot mate?'
}
```
Normally, I would loop through `users.$id.messages` and resolve the requests through a promise array. Then there would be some post processing to join the data on a new object.

- Does this library send a **single**, special request that let's Firebase know I'm looking for all of these records so multiple HTTP calls aren't made from loops? 

- Is post processing for joins also done server side or does the library do this when the payload comes back?

**Comment by katowulf** [comment]
All joining is done client side. This doesn't improve the download/upload performance, although it is fairly performant about how it conducts joins/et al. Note that this optimizes writes as well as reads, pushing set()/update() ops back to the correct paths.

Cheers,
Kato

**Comment by gigablox** [comment]
Got ya, so the joins are done client side.

What about the data coming back? Is that combined into a single payload or is it more of a promise array type deal?

**Comment by katowulf** [comment]
Have you checked out any of [the examples](http://firebase.github.io/firebase-util/#/toolbox/NormalizedCollection/)? They show the payload for each request.

**Comment by gigablox** [comment]
Yes I've built my own requests but you've just mentioned "All joining is done client side." in which case the label for "Joined Data (live)" is confusing to me.

To me "live" means what's returned by the server not what's done client side.

So is the "Raw Data (live)" payload coming back actually the blob of all the requested reads in a single payload or is it what is combined after a promise resolution client side?

**Comment by gigablox** [comment]
I guess the answer to my question was:

"This doesn't improve the download/upload performance, although it is fairly performant about how it conducts joins/et al."

Wondering if you guys are ever going to kick this up to the server in the future?

In my example if Jim has 500 older messages he want's to browse through they all need to be queried through a promise array.

I'm sure there's got to be a tipping point somewhere... any idea at what point the browser will start to struggle waiting for that payload to resolve and build itself?

**Comment by katowulf** [comment]
It's going to be highly subjective--really a product of the computer's computing capacity and memory. It seems like the best server-side solution would be to pre-compile the read data into a separate path. Some upcoming tools would assist with this. 

The performant solution for large data would probably be a server-side component, such as a node.js script, which would monitor the data and compile the joined results for read. Then clients would only need to listen on the compiled path for the pre-joined and rendered data.
