### ISSUE TITLE
Update firebase-util

### ISSUE THREAD

**Issue by michaeldim** [firebase/firebase-util#52]
Will there be a [firebase-release] with the fixes since May anytime soon? I would like to use them from the CDN/Bower. Thanks

**Comment by katowulf** [comment]
May was one a day ago. Which fixes, precisely, would you like to see released? Is there something in particular you're running into in 0.2.4?

**Comment by michaeldim** [comment]
It was just the OrderByValue() fix I was looking to use, #32.

**Comment by katowulf** [comment]
I'll see if we can push a release this week then. Cheers.

**Comment by michaeldim** [comment]
I would appreciate it, Thanks!

**Comment by jeromemodi** [comment]
Any news on this? 
A lot of issues have been resolved and the current library seems more stable than 0.2.4
I would like to use it from bower to easily integrate it in my project
Thanks

**Comment by katowulf** [comment]
Released [0.2.5](https://cdn.firebase.com/libs/firebase-util/0.2.5/firebase-util.min.js). Will update the site links shortly.

**Comment by jeromemodi** [comment]
Great news
Thanks Kato !
