### ISSUE TITLE
Better error message when attempting orderByChild() on Paginate or Scroll constructor

### ISSUE THREAD

**Issue by wandp** [firebase/firebase-util#53]
Trying to order my query by a timestamp:

     scrollRef.orderByChild('timestamp')
orderByChild is not supported for Paginate and Scroll references. Try calling it on the original reference used to create the instance instead.

    rootRef.orderByChild('timestamp')
Query.orderByChild: You can't combine multiple orderBy calls.

**Comment by wandp** [comment]
I see now that there sortBy field in the cache.
Perhaps a more informative error message here would alleviate some confusion.

**Comment by katowulf** [comment]
Thanks, leave this open and I'll look into the error message. A PR would of course be welcome.
