### ISSUE TITLE
Scroll + Normalized

### ISSUE THREAD

**Issue by bogdantmm92** [firebase/firebase-util#67]
This is not exactly an issue, but more of a question.
I have these lines:
```
var msgsRef = Utils.usersRef.child(this.props.userId).child('notebook/messages');
var scrollRef = new Firebase.util.Scroll(msgsRef, 'date');
var norm = new Firebase.util.NormalizedCollection(
       scrollRef,
       [membersRef, 'members', 'messages.fromId'],
       [Utils.ref.child('users'), 'users', 'messages.fromId']
    );
var normalizedRef = norm.select('......
```

I want to be able to paginate through the normalized ref. Any idea how to structure the refs?
If I try to compose the scrollRef out of normalizedRef, it gives me this error:
First argument to Firebase.util.Scroll must be a valid Firebase ref. It cannot be a Query (e.g. you have called orderByChild()).

**Comment by katowulf** [comment]
Create the normalized ref first and pass it into the Scroll/Paginate classes.

**Comment by laurensnl** [comment]
I did this:

'''
// map the paths we are going to join
var norm = new Firebase.util.NormalizedCollection(
	FB.child('sessions'),
	[FB.child('accounts'), 'accounts', 'sessions.user']
);

// specify the fields for each path
norm = norm.select( 'sessions.user', 'sessions.browser.platform', 'sessions.location.city', 'sessions.loginTime', 'sessions._sort', 'sessions.disconnectTime', 'accounts.profilePicture', 'accounts.displayName', 'accounts.airline' );
			
// get a reference we can use like a normal Firebase instance
var scrollRef = new Firebase.util.Scroll(norm.ref(), '_sort');
'''

The initial data is loaded correctly, but no subsequent data is loaded on scroll. Infinite scrolling does work when I replace the Normalized Collection ref to a standard Firebase ref. What am I doing wrong here?
