### ISSUE TITLE
paging with endAt/equalTo filters

### ISSUE THREAD

**Issue by sgavade** [firebase/firebase-util#68]
Hi,

I want to check if paging can be extended to also use filters such as equalTo, endAt. The current implementation allows me to pick a sort field but does not let me filter. Thoughts?

Regards,
Sameer

**Comment by katowulf** [comment]
It cannot and there are no plans to try and make it work within these constraints. As you can imagine, endAt/startAt are used heavily in the pagination code. Since you cannot nest queries in any way, this wouldn't be compatible.
