### ISSUE TITLE
When I use NormalizedCollection and Pagination util it doesn't work.

### ISSUE THREAD

**Issue by mifama** [firebase/firebase-util#70]
Hi, when I use the NormalizedCollection util and Pagination util it's doen't work together. In this case pagination return an error when i request for the next page. It's a javascript error this._ref.child() it's not a function of undefined.

I think it was very useful can be combinate NormalizedCollection  and Pagination

**Comment by katowulf** [comment]
Please provide an [mcve](http://stackoverflow.com/help/mcve) demonstrating the error. These utils work great together.

**Comment by mifama** [comment]
Hi, i make this example. The error is TypeError: this._ref.child is not a function
You can watch it.
