### ISSUE TITLE
Add data to snapshot value - extra trigger

### ISSUE THREAD

**Issue by lastuvka** [firebase/firebase-util#8]
If the firebaseRef is firebase-Util reference -> There is an interesting "bug" with this code:
firebaseRef.on('value', function(snapshot) {
   var data = snapshot.val();
   data.id = snapshot.name(); // add the key as an id
});
 The callback is trigger more times for one entry.

**Comment by katowulf** [comment]
Fixed in 0.2 where we'll have NormalizedCollection to replace the join functions.
