### ISSUE TITLE
Wrong documentation for limit

### ISSUE THREAD

**Issue by TrkiSF2** [firebase/firebase-util#9]
From your doc:

https://github.com/firebase/firebase-util/blob/master/src/join/README.md#queries-limit-startat-and-endat

    var indexRef = new Firebase('URL/index_path').limit(10);
    Firebase.util.intersection( indexRef, new Firebase('URL/data_path') );

![screenshot from 2014-05-02 16 11 13](https://cloud.githubusercontent.com/assets/3595242/2863395/157ddb08-d204-11e3-83ea-354af8f727c9.png)

![screenshot from 2014-05-02 16 11 26](https://cloud.githubusercontent.com/assets/3595242/2863398/19a2bc9e-d204-11e3-890a-00a42bdbfff2.png)

And my code
		        
                           var indexRef = new Firebase('path.com/'+subCategoryId).limit(10);
			                        var join = Firebase.util.intersection(
			                               	  indexRef,
			                  	               fbRefs.groups().child(subCategoryId)
		                            );
		                  return $firebase(join);

Using

    "firebase": "~1.0.13",
    "angularfire": "~0.7.1",

Error:

Error: Invalid path at position 0; it must be a valid Firebase or JoinedRecord instance, or if a props object is used, contain a ref key which is a valid instance
    at Object.PathLoader._assertValidPath (http://127.0.0.1:9000/bower_components/firebase-util/firebase-util.js:2870:22)
    at Array.forEach (native)
Is there a bug or am I doing something wrong please?

**Comment by CyberFerret** [comment]
Any updates on this issue?  I am experiencing the same thing using Firebase-util 0.1.0 from the CDN at the moment.

**Comment by katowulf** [comment]
0.2 will replace util.join with util.NormalizedCollection.
