### ISSUE TITLE
When will it be ready for production?

### ISSUE THREAD

**Issue by alejomendoza** [firebase/firebase-util#95]
Great idea! I think it will add a lot of value to Firebase. What I found so far is that I can not mold data the way a backend would do it because it has to be denormalized, same thing when writing and reading. The solution I had for now was to write a rest api on a node server and spin a couple of workers to process some of the data. I have a couple of questions:

1. When will it be ready for production?
2. Does it have support for Node.js ?

Thank you and this is amazing stuff, a tool to denormilze and normalize data reduces even more the need for a backend server.

**Comment by katowulf** [comment]
Thanks for the feedback! Should work great on Node. It will be ready for production when there is some usage and the bugs have been ironed out. This isn't at the top of the priority list, a couple months before it's likely to see much attention, but some participation and PRs would certainly move the beta status along and increase the priority.

**Comment by r3wt** [comment]
@katowulf a couple months? been nearly a year now.
